version: "3"

services:

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    tty: true
    hostname: server
    container_name: server
    environment:
      TF_TYPE: server
    volumes:
      - ./server/code:/app
    restart: always
    ports:
      - 1234:1234

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    tty: true
    environment:
      TF_TYPE: worker
    depends_on:
      - server
    volumes:
      - ./worker/code:/app
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - worker
    ports:
      - "4000:4000"
